// 敵キャラクター（にゃんこ帝国側）データ定義
// layer: 出現する層（sky=そら / ground=じめん / sea=うみ）
// minIndex: 出現しうる最小の通し進行度（tutorial=0, 第1章-1=1 ... 第5章-10=50）
// desc: 敵図鑑（ステージ選択画面の「👾 敵図鑑」）に表示する簡単な説明

import { UNIT_DEFS } from './units.js';

export const ENEMY_DEFS = [
  {
    id: 'noranyan',
    name: 'ノラニャン',
    attribute: 'none',
    icon: '🐱',
    layer: 'ground',
    minIndex: 0,
    desc: 'どこにでもいる野良のニャンコ。弱いが物おじせずまっすぐ突っ込んでくる。',
    hp: 100,
    atk: 25,
    atkInterval: 1500,
    range: 40,
    speed: 50,
    kb: 2,
    reward: 25,
    boss: false,
  },
  {
    id: 'akanyan',
    name: 'アカニャン',
    attribute: 'red',
    icon: '😾',
    layer: 'ground',
    minIndex: 1,
    desc: '赤い毛並みのニャンコ。ノラニャンよりタフで攻撃も強い、序盤の壁役。',
    hp: 170,
    atk: 55,
    atkInterval: 1300,
    range: 40,
    speed: 55,
    kb: 1,
    reward: 40,
    boss: false,
  },
  {
    id: 'fuwanyan',
    name: 'フワニャン',
    attribute: 'floating',
    icon: '👻',
    layer: 'sky',
    minIndex: 3,
    desc: 'ふわふわと宙を漂う幽霊ニャンコ。HPは低いがとにかく素早い。',
    hp: 70,
    atk: 15,
    atkInterval: 1000,
    range: 40,
    speed: 130,
    kb: 3,
    reward: 30,
    boss: false,
  },
  {
    id: 'uminyan',
    name: 'ウミニャン',
    attribute: 'none',
    icon: '🦑',
    layer: 'sea',
    minIndex: 7,
    desc: '海から現れるイカ型のニャンコ。うみの戦場でよく出会う標準的な敵。',
    hp: 140,
    atk: 35,
    atkInterval: 1400,
    range: 40,
    speed: 60,
    kb: 2,
    reward: 35,
    boss: false,
  },
  {
    id: 'kuronyan',
    name: 'クロニャン',
    attribute: 'black',
    icon: '🐈‍⬛',
    layer: 'ground',
    minIndex: 8,
    desc: '闇をまとう黒いニャンコ。アカニャンよりさらに硬く、殴り合いに強い。',
    hp: 240,
    atk: 75,
    atkInterval: 1200,
    range: 40,
    speed: 80,
    kb: 2,
    reward: 50,
    boss: false,
  },
  {
    id: 'tenshinyan',
    name: 'テンシニャン',
    attribute: 'angel',
    icon: '😇',
    layer: 'sky',
    minIndex: 11,
    desc: '天使の輪を頭にのせたそらの敵。射程が長く、近づく前から攻撃してくる。',
    hp: 260,
    atk: 60,
    atkInterval: 1100,
    range: 70,
    speed: 95,
    kb: 3,
    reward: 55,
    boss: false,
  },
  {
    id: 'aliennyan',
    name: 'エイリアンニャン',
    attribute: 'alien',
    icon: '👽',
    layer: 'sky',
    minIndex: 21,
    desc: '空飛ぶ円盤に乗った宇宙人ニャンコ。中盤のそらで一気に手強くなる。',
    hp: 420,
    atk: 110,
    atkInterval: 1000,
    range: 90,
    speed: 100,
    kb: 3,
    reward: 80,
    boss: false,
  },
  {
    id: 'ancientnyan',
    name: '古代ニャン',
    attribute: 'ancient',
    icon: '🗿',
    layer: 'ground',
    minIndex: 25,
    desc: '石像のような古代ニャンコ。動きは遅いが、とにかくHPが高い。',
    hp: 600,
    atk: 130,
    atkInterval: 1300,
    range: 40,
    speed: 65,
    kb: 4,
    reward: 100,
    boss: false,
  },
  {
    id: 'krakenpup',
    name: 'クラーケンの子',
    attribute: 'deep',
    icon: '🐙',
    layer: 'sea',
    minIndex: 31,
    desc: '深海に住む大ダコの子ども。うみの中盤で壁になる頼れない相手。',
    hp: 720,
    atk: 150,
    atkInterval: 1200,
    range: 50,
    speed: 70,
    kb: 4,
    reward: 120,
    boss: false,
  },
  {
    id: 'voidnyan',
    name: 'ヴォイドニャン',
    attribute: 'void',
    icon: '🌀',
    layer: 'sea',
    minIndex: 41,
    desc: '虚無の渦をまとうニャンコ。うみの終盤に出てくる高火力の敵。',
    hp: 900,
    atk: 180,
    atkInterval: 950,
    range: 80,
    speed: 110,
    kb: 4,
    reward: 150,
    boss: false,
  },
  {
    id: 'ohnyan-shogun',
    name: '大ニャン将軍',
    attribute: 'boss',
    icon: '👹',
    layers: ['ground', 'sky'],
    minIndex: 10,
    desc: '第1章のボス。じめんとそらにまたがる大柄な将軍で、最初の大きな壁。',
    hp: 4200,
    atk: 130,
    atkInterval: 1800,
    range: 60,
    speed: 30,
    kb: 8,
    reward: 500,
    boss: true,
  },
  {
    id: 'tenshi-shogun',
    name: '大天使ニャン',
    attribute: 'boss',
    icon: '👼',
    layers: ['sky', 'ground'],
    minIndex: 20,
    desc: '第2章のボス。巨大な翼を広げ、そら・じめんの両方に睨みを利かせる。',
    hp: 6800,
    atk: 170,
    atkInterval: 1700,
    range: 80,
    speed: 40,
    kb: 8,
    reward: 700,
    boss: true,
  },
  {
    id: 'alien-emperor',
    name: 'エイリアン皇帝',
    attribute: 'boss',
    icon: '🛸',
    layers: ['sky', 'ground'],
    minIndex: 30,
    desc: '第3章のボス。巨大円盤に乗る宇宙の皇帝。そら・じめんの両方を攻撃する。',
    hp: 10000,
    atk: 220,
    atkInterval: 1600,
    range: 90,
    speed: 35,
    kb: 9,
    reward: 1000,
    boss: true,
  },
  {
    id: 'kraken-shogun',
    name: '深海将軍クラーケン',
    attribute: 'boss',
    icon: '🦑',
    layers: ['sea', 'ground'],
    minIndex: 40,
    desc: '第4章のボス。巨大な触手でうみ・じめんの両方を薙ぎ払う深海の将軍。',
    hp: 14000,
    atk: 260,
    atkInterval: 1500,
    range: 100,
    speed: 38,
    kb: 10,
    reward: 1400,
    boss: true,
  },
  {
    id: 'nyandark-emperor',
    name: '終焉皇帝ニャンダーク',
    attribute: 'boss',
    icon: '🐲',
    layers: ['ground', 'sky'],
    minIndex: 50,
    desc: '第5章のボス。竜の姿をした闇の皇帝で、じめん・そらの両方で暴れる。',
    hp: 20000,
    atk: 320,
    atkInterval: 1400,
    range: 110,
    speed: 42,
    kb: 11,
    reward: 2000,
    boss: true,
  },
  {
    id: 'zombie-nyan-king',
    name: '亡者の王ゾンビニャン',
    attribute: 'boss',
    icon: '🧟',
    layers: ['sky', 'ground'],
    minIndex: 60,
    desc: '第6章のボス。亡者を率いる王で、そら・じめんの両方に腐敗の爪を振るう。',
    hp: 27000,
    atk: 380,
    atkInterval: 1300,
    range: 120,
    speed: 44,
    kb: 12,
    reward: 2700,
    boss: true,
  },
  {
    id: 'mecha-nyan-titan',
    name: '機械神ティターンニャン',
    attribute: 'boss',
    icon: '🤖',
    layers: ['sky', 'ground'],
    minIndex: 70,
    desc: '第7章のボス。巨大な機械の身体を持つ神で、そら・じめんの両方を制圧する。',
    hp: 35000,
    atk: 440,
    atkInterval: 1200,
    range: 130,
    speed: 46,
    kb: 12,
    reward: 3400,
    boss: true,
  },
  {
    id: 'frost-nyan-tyrant',
    name: '氷結皇ニャンフロスト',
    attribute: 'boss',
    icon: '❄️',
    layers: ['ground', 'sea'],
    minIndex: 80,
    desc: '第8章のボス。氷の暴君で、じめん・うみの両方を凍りつかせる。',
    hp: 45000,
    atk: 510,
    atkInterval: 1100,
    range: 140,
    speed: 48,
    kb: 13,
    reward: 4300,
    boss: true,
  },
  {
    id: 'magma-nyan-overlord',
    name: '溶岩魔王マグマニャン',
    attribute: 'boss',
    icon: '🌋',
    layers: ['ground', 'sky'],
    minIndex: 90,
    desc: '第9章のボス。溶岩をまとう魔王で、じめん・そらの両方を焼き尽くす。',
    hp: 58000,
    atk: 590,
    atkInterval: 1000,
    range: 150,
    speed: 50,
    kb: 14,
    reward: 5400,
    boss: true,
  },
  {
    id: 'omega-nyan-god',
    name: '全能神オメガニャン',
    attribute: 'boss',
    icon: '♾️',
    layers: ['sky', 'ground', 'sea'],
    minIndex: 100,
    desc: '第10章の最終ボス。そら・じめん・うみの3層すべてを支配する全能の神。',
    hp: 75000,
    atk: 700,
    atkInterval: 900,
    range: 160,
    speed: 55,
    kb: 15,
    reward: 7000,
    boss: true,
  },
  // ---- エクストラステージ専用ボス（メインの章進行とは別枠。通常より大幅に強い） ----
  {
    id: 'phantom-baron-nyan',
    name: '亡影男爵ファントムニャン',
    attribute: 'boss',
    icon: '🎭',
    layers: ['ground', 'sea'],
    minIndex: 35,
    desc: 'エクストラ1のボス。仮面の男爵が、じめん・うみの両方に幻影の一撃を放つ。',
    hp: 32000,
    atk: 420,
    atkInterval: 1250,
    range: 110,
    speed: 46,
    kb: 12,
    reward: 3000,
    boss: true,
  },
  {
    id: 'chaos-nyan-dragon',
    name: '混沌竜カオスニャン',
    attribute: 'boss',
    icon: '🐉',
    layers: ['sky', 'sea'],
    minIndex: 65,
    desc: 'エクストラ2のボス。混沌をまとう竜で、そら・うみの両方を荒らし回る。',
    hp: 68000,
    atk: 730,
    atkInterval: 1050,
    range: 140,
    speed: 50,
    kb: 14,
    reward: 6000,
    boss: true,
  },
  {
    id: 'true-nyan-god-eternal',
    name: '真・永劫神ニャン',
    attribute: 'boss',
    icon: '🌌',
    layers: ['sky', 'ground', 'sea'],
    minIndex: 100,
    desc: 'エクストラ3のボス。3層すべてを支配する永劫の神。エクストラ最強格。',
    hp: 260000,
    atk: 1400,
    atkInterval: 800,
    range: 180,
    speed: 65,
    kb: 20,
    reward: 20000,
    boss: true,
  },
  // ---- むずかしい専用エクストラのボス（さらに難易度倍率 x1.35 がかかる） ----
  {
    id: 'tempest-nyan-knight',
    name: '嵐騎士テンペストニャン',
    attribute: 'boss',
    icon: '🌪️',
    layers: ['sky', 'ground'],
    minIndex: 45,
    desc: 'むずかしい専用エクストラ1のボス。暴風をまとう騎士が、そら・じめんを薙ぎ払う。',
    hp: 42000,
    atk: 500,
    atkInterval: 1150,
    range: 120,
    speed: 48,
    kb: 12,
    reward: 4000,
    boss: true,
  },
  {
    id: 'abyss-nyan-leviathan',
    name: '深淵獣リヴァイアニャン',
    attribute: 'boss',
    icon: '🐋',
    layers: ['ground', 'sea'],
    minIndex: 75,
    desc: 'むずかしい専用エクストラ2のボス。深淵に住む巨獣が、じめん・うみに襲いかかる。',
    hp: 85000,
    atk: 800,
    atkInterval: 1050,
    range: 150,
    speed: 50,
    kb: 14,
    reward: 7000,
    boss: true,
  },
  {
    id: 'genesis-nyan-machine',
    name: '創世機神ジェネシスニャン',
    attribute: 'boss',
    icon: '🛰️',
    layers: ['sky', 'ground', 'sea'],
    minIndex: 100,
    desc: 'むずかしい専用エクストラ3のボス。3層すべてを支配する創世の機神。',
    hp: 280000,
    atk: 1450,
    atkInterval: 800,
    range: 180,
    speed: 62,
    kb: 20,
    reward: 22000,
    boss: true,
  },
  // ---- ゲキむず専用エクストラのボス（さらに難易度倍率 x1.8 がかかる） ----
  {
    id: 'inferno-nyan-oni',
    name: '獄炎鬼インフェルニャン',
    attribute: 'boss',
    icon: '👺',
    layers: ['sky', 'ground'],
    minIndex: 55,
    desc: 'ゲキむず専用エクストラ1のボス。業火をまとう鬼が、そら・じめんを焼き払う。',
    hp: 50000,
    atk: 600,
    atkInterval: 1100,
    range: 130,
    speed: 50,
    kb: 13,
    reward: 5000,
    boss: true,
  },
  {
    id: 'eclipse-nyan-queen',
    name: '日蝕女王エクリプスニャン',
    attribute: 'boss',
    icon: '🌑',
    layers: ['sky', 'sea'],
    minIndex: 85,
    desc: 'ゲキむず専用エクストラ2のボス。太陽を喰らう女王が、そら・うみを闇に染める。',
    hp: 95000,
    atk: 880,
    atkInterval: 1000,
    range: 160,
    speed: 52,
    kb: 15,
    reward: 8000,
    boss: true,
  },
  {
    id: 'zero-nyan-origin',
    name: '零式始神ゼロニャン',
    attribute: 'boss',
    icon: '🌀',
    layers: ['sky', 'ground', 'sea'],
    minIndex: 100,
    desc: 'ゲキむず専用エクストラ3のボス。全ての始まりにして全ての層を支配する最強の敵。',
    hp: 300000,
    atk: 1500,
    atkInterval: 780,
    range: 190,
    speed: 65,
    kb: 22,
    reward: 25000,
    boss: true,
  },
];

// ---- ハロウィンイベント専用の敵（通常の章・エクストラには出ない） ----
// プレイヤー側のハロウィン仮装キャラ12体がそのまま敵として出てくる（画像も同じものを左右反転して使う）。
// ボスは伝説レアのキャラ。ステージごとの強さは waves の statMult で調整する。
export const HALLOWEEN_EVENT_BOSS_UNIT_IDS = ['cerberus', 'seiryu-inu', 'elemental-husky-god', 'fenrir', 'cosmos-goddess'];

function enemyFromUnit(unit, boss) {
  // ユニットのflavorは「〇〇限定・レア度。本文」の形式なので、入手方法を説明する先頭の一文は敵図鑑では不要
  const flavorBody = (unit.flavor || '').replace(/^[^。]*限定・[^。]*。/, '');
  return {
    id: `${boss ? 'hw-boss' : 'hw'}-${unit.id}`,
    name: unit.name,
    attribute: boss ? 'boss' : 'none',
    icon: unit.icon,
    imageDefId: unit.id,
    desc: (boss ? 'ハロウィンイベントのボスとして立ちはだかる。' : 'ハロウィンの夜、敵として現れた仮装わんこ。') + flavorBody,
    layer: unit.layer,
    minIndex: Infinity,
    eventOnly: true,
    hp: boss ? unit.hp * 10 : unit.hp,
    atk: boss ? Math.round(unit.atk * 1.4) : unit.atk,
    atkInterval: unit.atkInterval,
    range: unit.range,
    speed: boss ? Math.round(unit.speed * 0.6) : unit.speed,
    kb: boss ? 12 : unit.kb,
    reward: boss ? 1500 : Math.round(unit.cost / 3),
    boss,
  };
}

ENEMY_DEFS.push(
  ...UNIT_DEFS.filter((u) => u.isHalloween).map((u) => enemyFromUnit(u, false)),
  ...HALLOWEEN_EVENT_BOSS_UNIT_IDS.map((id) => enemyFromUnit(UNIT_DEFS.find((u) => u.id === id), true))
);

export function getEnemyDef(id) {
  return ENEMY_DEFS.find((e) => e.id === id);
}

let uidCounter = 0;

export function spawnEnemy(defId, x, statMult = 1) {
  const def = getEnemyDef(defId);
  if (!def) throw new Error(`unknown enemy: ${defId}`);
  const hp = Math.round(def.hp * statMult);
  return {
    uid: `e${++uidCounter}`,
    defId,
    side: 'enemy',
    name: def.name,
    icon: def.icon,
    imageDefId: def.imageDefId,
    layer: def.layer,
    layers: def.layers,
    attribute: def.attribute,
    boss: def.boss,
    x,
    width: def.layers ? 72 : def.boss ? 56 : 34,
    hp,
    maxHp: hp,
    atk: Math.round(def.atk * statMult),
    atkInterval: def.atkInterval,
    range: def.range,
    speed: def.speed,
    reward: def.reward,
    kbRemaining: def.kb,
    nextAttackAt: 0,
    attackFlashUntil: 0,
    knockbackUntil: 0,
    engaged: false,
    dead: false,
  };
}
