// 敵キャラクター（にゃんこ帝国側）データ定義
// layer: 出現する層（sky=そら / ground=じめん / sea=うみ）
// minIndex: 出現しうる最小の通し進行度（tutorial=0, 第1章-1=1 ... 第5章-10=50）

export const ENEMY_DEFS = [
  {
    id: 'noranyan',
    name: 'ノラニャン',
    attribute: 'none',
    icon: '🐱',
    layer: 'ground',
    minIndex: 0,
    hp: 100,
    atk: 25,
    atkInterval: 1500,
    range: 40,
    speed: 50,
    kb: 2,
    reward: 25,
    boss: false,
  },
  {
    id: 'akanyan',
    name: 'アカニャン',
    attribute: 'red',
    icon: '😾',
    layer: 'ground',
    minIndex: 1,
    hp: 170,
    atk: 55,
    atkInterval: 1300,
    range: 40,
    speed: 55,
    kb: 1,
    reward: 40,
    boss: false,
  },
  {
    id: 'fuwanyan',
    name: 'フワニャン',
    attribute: 'floating',
    icon: '👻',
    layer: 'sky',
    minIndex: 3,
    hp: 70,
    atk: 15,
    atkInterval: 1000,
    range: 40,
    speed: 130,
    kb: 3,
    reward: 30,
    boss: false,
  },
  {
    id: 'uminyan',
    name: 'ウミニャン',
    attribute: 'none',
    icon: '🦑',
    layer: 'sea',
    minIndex: 7,
    hp: 140,
    atk: 35,
    atkInterval: 1400,
    range: 40,
    speed: 60,
    kb: 2,
    reward: 35,
    boss: false,
  },
  {
    id: 'kuronyan',
    name: 'クロニャン',
    attribute: 'black',
    icon: '🐈‍⬛',
    layer: 'ground',
    minIndex: 8,
    hp: 240,
    atk: 75,
    atkInterval: 1200,
    range: 40,
    speed: 80,
    kb: 2,
    reward: 50,
    boss: false,
  },
  {
    id: 'tenshinyan',
    name: 'テンシニャン',
    attribute: 'angel',
    icon: '😇',
    layer: 'sky',
    minIndex: 11,
    hp: 260,
    atk: 60,
    atkInterval: 1100,
    range: 70,
    speed: 95,
    kb: 3,
    reward: 55,
    boss: false,
  },
  {
    id: 'aliennyan',
    name: 'エイリアンニャン',
    attribute: 'alien',
    icon: '👽',
    layer: 'sky',
    minIndex: 21,
    hp: 420,
    atk: 110,
    atkInterval: 1000,
    range: 90,
    speed: 100,
    kb: 3,
    reward: 80,
    boss: false,
  },
  {
    id: 'ancientnyan',
    name: '古代ニャン',
    attribute: 'ancient',
    icon: '🗿',
    layer: 'ground',
    minIndex: 25,
    hp: 600,
    atk: 130,
    atkInterval: 1300,
    range: 40,
    speed: 65,
    kb: 4,
    reward: 100,
    boss: false,
  },
  {
    id: 'krakenpup',
    name: 'クラーケンの子',
    attribute: 'deep',
    icon: '🐙',
    layer: 'sea',
    minIndex: 31,
    hp: 720,
    atk: 150,
    atkInterval: 1200,
    range: 50,
    speed: 70,
    kb: 4,
    reward: 120,
    boss: false,
  },
  {
    id: 'voidnyan',
    name: 'ヴォイドニャン',
    attribute: 'void',
    icon: '🌀',
    layer: 'sea',
    minIndex: 41,
    hp: 900,
    atk: 180,
    atkInterval: 950,
    range: 80,
    speed: 110,
    kb: 4,
    reward: 150,
    boss: false,
  },
  {
    id: 'ohnyan-shogun',
    name: '大ニャン将軍',
    attribute: 'boss',
    icon: '👹',
    layers: ['ground', 'sky'],
    minIndex: 10,
    hp: 4200,
    atk: 130,
    atkInterval: 1800,
    range: 60,
    speed: 30,
    kb: 8,
    reward: 500,
    boss: true,
  },
  {
    id: 'tenshi-shogun',
    name: '大天使ニャン',
    attribute: 'boss',
    icon: '👼',
    layers: ['sky', 'ground'],
    minIndex: 20,
    hp: 6800,
    atk: 170,
    atkInterval: 1700,
    range: 80,
    speed: 40,
    kb: 8,
    reward: 700,
    boss: true,
  },
  {
    id: 'alien-emperor',
    name: 'エイリアン皇帝',
    attribute: 'boss',
    icon: '🛸',
    layers: ['sky', 'ground'],
    minIndex: 30,
    hp: 10000,
    atk: 220,
    atkInterval: 1600,
    range: 90,
    speed: 35,
    kb: 9,
    reward: 1000,
    boss: true,
  },
  {
    id: 'kraken-shogun',
    name: '深海将軍クラーケン',
    attribute: 'boss',
    icon: '🦑',
    layers: ['sea', 'ground'],
    minIndex: 40,
    hp: 14000,
    atk: 260,
    atkInterval: 1500,
    range: 100,
    speed: 38,
    kb: 10,
    reward: 1400,
    boss: true,
  },
  {
    id: 'nyandark-emperor',
    name: '終焉皇帝ニャンダーク',
    attribute: 'boss',
    icon: '🐲',
    layers: ['ground', 'sky'],
    minIndex: 50,
    hp: 20000,
    atk: 320,
    atkInterval: 1400,
    range: 110,
    speed: 42,
    kb: 11,
    reward: 2000,
    boss: true,
  },
  {
    id: 'zombie-nyan-king',
    name: '亡者の王ゾンビニャン',
    attribute: 'boss',
    icon: '🧟',
    layers: ['ground', 'sea'],
    minIndex: 60,
    hp: 27000,
    atk: 380,
    atkInterval: 1300,
    range: 120,
    speed: 44,
    kb: 12,
    reward: 2700,
    boss: true,
  },
  {
    id: 'mecha-nyan-titan',
    name: '機械神ティターンニャン',
    attribute: 'boss',
    icon: '🤖',
    layers: ['sky', 'ground'],
    minIndex: 70,
    hp: 35000,
    atk: 440,
    atkInterval: 1200,
    range: 130,
    speed: 46,
    kb: 12,
    reward: 3400,
    boss: true,
  },
  {
    id: 'frost-nyan-tyrant',
    name: '氷結皇ニャンフロスト',
    attribute: 'boss',
    icon: '❄️',
    layers: ['ground', 'sea'],
    minIndex: 80,
    hp: 45000,
    atk: 510,
    atkInterval: 1100,
    range: 140,
    speed: 48,
    kb: 13,
    reward: 4300,
    boss: true,
  },
  {
    id: 'magma-nyan-overlord',
    name: '溶岩魔王マグマニャン',
    attribute: 'boss',
    icon: '🌋',
    layers: ['ground', 'sky'],
    minIndex: 90,
    hp: 58000,
    atk: 590,
    atkInterval: 1000,
    range: 150,
    speed: 50,
    kb: 14,
    reward: 5400,
    boss: true,
  },
  {
    id: 'omega-nyan-god',
    name: '全能神オメガニャン',
    attribute: 'boss',
    icon: '♾️',
    layers: ['sky', 'ground', 'sea'],
    minIndex: 100,
    hp: 75000,
    atk: 700,
    atkInterval: 900,
    range: 160,
    speed: 55,
    kb: 15,
    reward: 7000,
    boss: true,
  },
  // ---- エクストラステージ専用ボス（メインの章進行とは別枠。通常より大幅に強い） ----
  {
    id: 'phantom-baron-nyan',
    name: '亡影男爵ファントムニャン',
    attribute: 'boss',
    icon: '🎭',
    layers: ['ground', 'sea'],
    minIndex: 35,
    hp: 32000,
    atk: 420,
    atkInterval: 1250,
    range: 110,
    speed: 46,
    kb: 12,
    reward: 3000,
    boss: true,
  },
  {
    id: 'chaos-nyan-dragon',
    name: '混沌竜カオスニャン',
    attribute: 'boss',
    icon: '🐉',
    layers: ['sky', 'sea'],
    minIndex: 65,
    hp: 68000,
    atk: 730,
    atkInterval: 1050,
    range: 140,
    speed: 50,
    kb: 14,
    reward: 6000,
    boss: true,
  },
  {
    id: 'true-nyan-god-eternal',
    name: '真・永劫神ニャン',
    attribute: 'boss',
    icon: '🌌',
    layers: ['sky', 'ground', 'sea'],
    minIndex: 100,
    hp: 260000,
    atk: 1400,
    atkInterval: 800,
    range: 180,
    speed: 65,
    kb: 20,
    reward: 20000,
    boss: true,
  },
];

export function getEnemyDef(id) {
  return ENEMY_DEFS.find((e) => e.id === id);
}

let uidCounter = 0;

export function spawnEnemy(defId, x, statMult = 1) {
  const def = getEnemyDef(defId);
  if (!def) throw new Error(`unknown enemy: ${defId}`);
  const hp = Math.round(def.hp * statMult);
  return {
    uid: `e${++uidCounter}`,
    defId,
    side: 'enemy',
    name: def.name,
    icon: def.icon,
    layer: def.layer,
    layers: def.layers,
    attribute: def.attribute,
    boss: def.boss,
    x,
    width: def.layers ? 72 : def.boss ? 56 : 34,
    hp,
    maxHp: hp,
    atk: Math.round(def.atk * statMult),
    atkInterval: def.atkInterval,
    range: def.range,
    speed: def.speed,
    reward: def.reward,
    kbRemaining: def.kb,
    nextAttackAt: 0,
    attackFlashUntil: 0,
    knockbackUntil: 0,
    engaged: false,
    dead: false,
  };
}
