// プレイヤーキャラクター（わんこ側）データ定義
// layer: 戦いに参加できる層（sky=上空 / mid=中空 / ground=地面 / sea=海面）
// rarity: basic（最初から） / EX（章ボス撃破報酬） / rare・superrare・legend（ガチャ限定）

export const MAX_LEVEL = 30;
export const BASE_LEVEL_CAP = 5; // ガチャ限定キャラの初期レベル上限（限界突破前）
export const LIMIT_BREAK_STEP = 5; // 重複キャラ1体を素材にレベル上限を+5
const LEVEL_PER_STEP = 0.06; // レベル1につき HP/攻撃力 +6%（緩やかな成長）
const FORM_LEVEL_SPAN = 10; // 10レベルごとに進化
const FORM_BONUS = [1, 1.3, 1.7]; // 進化時の大幅ボーナス（第1形態/第2形態/第3形態）
export const FORM_SUFFIX = ['', '【改】', '【真】'];
export const FORM_BADGE = ['', '⚔️', '👑'];

// 基本キャラ（最初から仲間）は最初からLv上限まで育成可能。
// ガチャ限定キャラ（EX・レア・超激レア・伝説レア）は同キャラの重複入手を
// 限界突破の素材にして5レベルずつ上限を伸ばしていく必要がある。
export function getEffectiveMaxLevel(def, limitBreakCount = 0) {
  if (def.rarity === 'basic') return MAX_LEVEL;
  return Math.min(MAX_LEVEL, BASE_LEVEL_CAP + limitBreakCount * LIMIT_BREAK_STEP);
}

export function getFormIndex(level) {
  return Math.min(FORM_BONUS.length - 1, Math.floor(Math.max(1, level) / FORM_LEVEL_SPAN));
}

export function getFormSuffix(level) {
  return FORM_SUFFIX[getFormIndex(level)];
}

export function getFormBadge(level) {
  return FORM_BADGE[getFormIndex(level)];
}

// キャラ画像のパス（すべて assets/ 配下、index.htmlからの相対パス）
export function getStatusImage(defId) {
  return `assets/characters/status/${defId}.png`;
}

export function getBattleImage(defId) {
  return `assets/characters/battle/${defId}.png`;
}

// レアリティ別の「きらきら背景」。ステータス用画像の背景として重ねる
export function getKirakiraImage(rarity) {
  return `assets/kirakira/${rarity.toLowerCase()}.png`;
}

// 自城に据え付けられた武器。他のキャラと同様に出撃コスト（コイン）が必要だが、
// HPは持たず撃破されない。一度出撃させれば戦闘終了まで再出撃なしで稼働し続ける。
// 中距離砲は手数重視、遠距離砲は一撃の重さ重視で、どちらも全レイヤーの敵を狙える。
export const CASTLE_WEAPONS = [
  {
    id: 'castle-midgun',
    name: '城砲・中距離砲台',
    icon: '🔫',
    range: 220,
    atk: 90,
    atkInterval: 1400,
    cost: 200,
    startUnlocked: true,
    flavor: '自城に備え付けられた速射砲。中距離に迫る敵を牽制する。',
  },
  {
    id: 'castle-longgun',
    name: '城砲・遠距離砲台',
    icon: '🎆',
    range: 420,
    atk: 170,
    atkInterval: 2800,
    cost: 350,
    startUnlocked: true,
    flavor: '自城の主砲。遠距離から重い一撃を撃ち込む。',
  },
  // ---- エクストラステージ撃破報酬。最初は未解放で、対応するエクストラステージをクリアすると使えるようになる ----
  {
    id: 'castle-shadow-cannon',
    name: '城砲・影撃砲',
    icon: '🌑',
    range: 380,
    atk: 280,
    atkInterval: 2000,
    cost: 550,
    startUnlocked: false,
    flavor: 'エクストラ1「亡影の迷宮」制覇の証。闇を纏った一撃を放つ。',
  },
  {
    id: 'castle-chaos-blaster',
    name: '城砲・混沌砲',
    icon: '🔮',
    range: 460,
    atk: 420,
    atkInterval: 2400,
    cost: 700,
    startUnlocked: false,
    flavor: 'エクストラ2「混沌の竜穴」制覇の証。竜の力を凝縮した砲撃。',
  },
  {
    id: 'castle-eternal-railgun',
    name: '城砲・永劫レールガン',
    icon: '✨',
    range: 600,
    atk: 650,
    atkInterval: 3000,
    cost: 950,
    startUnlocked: false,
    flavor: 'エクストラ3「永劫の終着点」制覇の証。わんこ王国最強の砲。',
  },
];

export const UNIT_DEFS = [
  {
    id: 'wankou',
    name: 'ワンコウ',
    breed: '柴犬',
    role: 'バランス',
    icon: '🐕',
    layer: 'ground',
    rarity: 'basic',
    cost: 75,
    hp: 250,
    atk: 45,
    atkInterval: 1200,
    range: 40,
    speed: 90,
    kb: 3,
    recast: 3000,
    strongAgainst: [],
    startUnlocked: true,
    flavor: '全属性に対応できる、王国軍の基本兵。地上を駆ける。',
  },
  {
    id: 'shibaruru',
    name: 'シバルル',
    breed: '柴犬',
    role: '壁役',
    icon: '🐩',
    layer: 'ground',
    rarity: 'basic',
    cost: 100,
    hp: 1000,
    atk: 15,
    atkInterval: 1400,
    range: 40,
    speed: 60,
    kb: 1,
    recast: 5000,
    strongAgainst: [],
    startUnlocked: true,
    flavor: '激安の大型犬。ほとんど怯まず地上の前線を支える。',
  },
  {
    id: 'terrials',
    name: 'テリアルス',
    breed: 'テリア',
    role: '高速アタッカー',
    icon: '🐶',
    layer: 'mid',
    rarity: 'basic',
    cost: 150,
    hp: 220,
    atk: 70,
    atkInterval: 900,
    range: 50,
    speed: 160,
    kb: 2,
    recast: 6000,
    strongAgainst: ['floating'],
    startUnlocked: true,
    flavor: '中空を飛び回り、浮いてる敵を追い回す俊足のテリア。',
  },
  {
    id: 'basset',
    name: 'バセット',
    breed: 'バセットハウンド',
    role: '遠距離砲撃',
    icon: '🦮',
    layer: 'sea',
    rarity: 'basic',
    cost: 300,
    hp: 380,
    atk: 260,
    atkInterval: 2200,
    range: 250,
    speed: 70,
    kb: 2,
    recast: 12000,
    strongAgainst: ['red'],
    startUnlocked: true,
    flavor: '海面を渡る筏の上から、射程の長い一撃で赤い敵を狙い撃つ。',
  },
  {
    id: 'dogimine',
    name: 'ドギミネ',
    breed: 'スピッツ',
    role: '中距離攻撃',
    icon: '🐺',
    layer: 'sky',
    rarity: 'basic',
    cost: 200,
    hp: 300,
    atk: 130,
    atkInterval: 1500,
    range: 160,
    speed: 85,
    kb: 3,
    recast: 8000,
    strongAgainst: ['black'],
    startUnlocked: true,
    flavor: '上空から中距離攻撃で着実にダメージを重ねる。',
  },
  {
    id: 'corgi-commander',
    name: 'コマンダー',
    breed: 'コーギー',
    role: '撃破指揮官',
    icon: '🐕‍🦺',
    layer: 'ground',
    rarity: 'EX',
    cost: 220,
    hp: 420,
    atk: 140,
    atkInterval: 1100,
    range: 90,
    speed: 110,
    kb: 4,
    recast: 9000,
    strongAgainst: ['boss'],
    startUnlocked: false,
    flavor: 'ガチャ限定・EX。大ニャン将軍を討ち取った伝説の空挺犬部隊、その指揮官。ボス級の敵に的確な一撃を叩き込む。',
  },
  {
    id: 'moon-husky',
    name: 'ツキカゲ',
    breed: 'シベリアンハスキー',
    role: '夜間急襲',
    icon: '🐺',
    layer: 'sky',
    rarity: 'EX',
    cost: 260,
    hp: 360,
    atk: 170,
    atkInterval: 950,
    range: 110,
    speed: 140,
    kb: 3,
    recast: 9000,
    strongAgainst: ['angel'],
    startUnlocked: false,
    flavor: 'ガチャ限定・EX。大天使ニャンを討ち取った夜襲部隊のエース。上空で天使系の敵を斬り伏せる。',
  },
  {
    id: 'cosmo-bernese',
    name: 'コスモ',
    breed: 'バーニーズ・マウンテン・ドッグ',
    role: '最終決戦兵器',
    icon: '🐕‍🦺',
    layer: 'ground',
    rarity: 'EX',
    cost: 340,
    hp: 700,
    atk: 200,
    atkInterval: 1300,
    range: 120,
    speed: 100,
    kb: 5,
    recast: 13000,
    strongAgainst: ['alien', 'ancient'],
    startUnlocked: false,
    flavor: 'ガチャ限定・EX。エイリアン皇帝を討ち取った星間遠征軍の切り札。エイリアンにも古代種にも動じない。',
  },
  {
    id: 'triton-hound',
    name: 'トリトン',
    breed: 'ポルトガル・ウォーター・ドッグ',
    role: '深海掃討',
    icon: '🌊',
    layer: 'sea',
    rarity: 'EX',
    cost: 280,
    hp: 480,
    atk: 165,
    atkInterval: 1150,
    range: 100,
    speed: 105,
    kb: 4,
    recast: 9500,
    strongAgainst: ['deep'],
    startUnlocked: false,
    flavor: 'ガチャ限定・EX。深海将軍クラーケンを討ち取った海底遠征隊の猟犬。',
  },
  {
    id: 'ragna-emperor',
    name: 'ラグナ',
    breed: '謎の古代犬種',
    role: '終焉の裁定者',
    icon: '🌌',
    layer: 'sky',
    rarity: 'EX',
    cost: 360,
    hp: 640,
    atk: 210,
    atkInterval: 1200,
    range: 130,
    speed: 115,
    kb: 5,
    recast: 13500,
    strongAgainst: ['void', 'boss'],
    startUnlocked: false,
    flavor: 'ガチャ限定・EX。終焉皇帝ニャンダークを討ち取った、時空の狭間から現れし裁定者。',
  },
  {
    id: 'dachs-fighter',
    name: 'ダックス',
    breed: 'ダックスフンド',
    role: '低空強襲',
    icon: '🌭',
    layer: 'ground',
    rarity: 'rare',
    cost: 180,
    hp: 320,
    atk: 100,
    atkInterval: 1000,
    range: 60,
    speed: 100,
    kb: 3,
    recast: 6500,
    strongAgainst: ['red'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・レア。低い車高を活かして懐に潜り込む。',
  },
  {
    id: 'pome-sho',
    name: 'ショウ',
    breed: 'ポメラニアン',
    role: '高速遊撃',
    icon: '🧨',
    layer: 'sky',
    rarity: 'rare',
    cost: 190,
    hp: 260,
    atk: 95,
    atkInterval: 800,
    range: 100,
    speed: 170,
    kb: 2,
    recast: 6000,
    strongAgainst: ['floating'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・レア。ふわふわの毛並みで空を舞う遊撃手。',
  },
  {
    id: 'beagle-scout',
    name: 'セッコウ',
    breed: 'ビーグル',
    role: '偵察襲撃',
    icon: '🎯',
    layer: 'ground',
    rarity: 'rare',
    cost: 150,
    hp: 260,
    atk: 85,
    atkInterval: 1000,
    range: 70,
    speed: 105,
    kb: 3,
    recast: 6000,
    strongAgainst: ['none'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・レア。鋭い嗅覚で無属性の敵を的確に狩る。',
  },
  {
    id: 'shiba-ronin',
    name: 'ロウニン',
    breed: '柴犬',
    role: '一刀両断',
    icon: '🗡️',
    layer: 'ground',
    rarity: 'rare',
    cost: 170,
    hp: 300,
    atk: 120,
    atkInterval: 1300,
    range: 55,
    speed: 90,
    kb: 3,
    recast: 6800,
    strongAgainst: ['red'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・レア。流浪の剣豪犬。一太刀の重さは並みではない。',
  },
  {
    id: 'poodle-mage',
    name: 'マドウシ',
    breed: 'トイプードル',
    role: '魔法支援',
    icon: '🔮',
    layer: 'mid',
    rarity: 'rare',
    cost: 160,
    hp: 230,
    atk: 80,
    atkInterval: 1100,
    range: 180,
    speed: 80,
    kb: 2,
    recast: 6500,
    strongAgainst: ['floating', 'angel'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・レア。中空に浮遊する敵を魔法弾で撃ち落とす。',
  },
  {
    id: 'akita-guard',
    name: 'ゴエイ',
    breed: '秋田犬',
    role: '盾役',
    icon: '🛡️',
    layer: 'ground',
    rarity: 'rare',
    cost: 140,
    hp: 550,
    atk: 40,
    atkInterval: 1500,
    range: 40,
    speed: 55,
    kb: 1,
    recast: 5500,
    strongAgainst: [],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・レア。忠義に厚く、前線を決して譲らない盾役。',
  },
  {
    id: 'whippet-dash',
    name: 'シップウ',
    breed: 'ウィペット',
    role: '高速強襲',
    icon: '💨',
    layer: 'sky',
    rarity: 'rare',
    cost: 180,
    hp: 210,
    atk: 90,
    atkInterval: 750,
    range: 90,
    speed: 190,
    kb: 2,
    recast: 5800,
    strongAgainst: ['floating'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・レア。陸上最速の犬種が空でもその速さを発揮する。',
  },
  {
    id: 'labrador-diver',
    name: 'センスイシ',
    breed: 'ラブラドール・レトリバー',
    role: '潜航攻撃',
    icon: '🤿',
    layer: 'sea',
    rarity: 'rare',
    cost: 190,
    hp: 340,
    atk: 100,
    atkInterval: 1200,
    range: 60,
    speed: 85,
    kb: 3,
    recast: 6600,
    strongAgainst: ['deep'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・レア。海面下に潜み、深海の敵を待ち伏せる。',
  },
  {
    id: 'greatdane-emperor',
    name: 'タイテイ',
    breed: 'グレート・デーン',
    role: '重装砲撃',
    icon: '🔱',
    layer: 'sea',
    rarity: 'superrare',
    cost: 320,
    hp: 520,
    atk: 230,
    atkInterval: 1600,
    range: 200,
    speed: 90,
    kb: 4,
    recast: 10000,
    strongAgainst: ['black', 'angel'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・超激レア。海面を制する巨躯の皇帝。',
  },
  {
    id: 'mastiff-titan',
    name: 'タイタン',
    breed: 'イングリッシュ・マスティフ',
    role: '重装突撃',
    icon: '🏔️',
    layer: 'ground',
    rarity: 'superrare',
    cost: 340,
    hp: 750,
    atk: 200,
    atkInterval: 1400,
    range: 60,
    speed: 75,
    kb: 5,
    recast: 10500,
    strongAgainst: ['black', 'ancient'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・超激レア。山のような巨体で前線を押し潰す。',
  },
  {
    id: 'bordercollie-strategist',
    name: 'グンシ',
    breed: 'ボーダー・コリー',
    role: '戦術支援',
    icon: '🧭',
    layer: 'mid',
    rarity: 'superrare',
    cost: 300,
    hp: 380,
    atk: 180,
    atkInterval: 1000,
    range: 170,
    speed: 100,
    kb: 3,
    recast: 9500,
    strongAgainst: ['floating', 'angel'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・超激レア。中空の戦況を見通す名軍師。',
  },
  {
    id: 'shepherd-marshal',
    name: 'ゲンスイ',
    breed: 'ジャーマン・シェパード',
    role: '空中司令',
    icon: '🎖️',
    layer: 'sky',
    rarity: 'superrare',
    cost: 330,
    hp: 420,
    atk: 210,
    atkInterval: 1050,
    range: 140,
    speed: 130,
    kb: 4,
    recast: 10000,
    strongAgainst: ['angel', 'alien'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・超激レア。上空の戦線を統率する元帥。',
  },
  {
    id: 'newfoundland-admiral',
    name: 'テイトク',
    breed: 'ニューファンドランド',
    role: '海将',
    icon: '⚓',
    layer: 'sea',
    rarity: 'superrare',
    cost: 350,
    hp: 620,
    atk: 190,
    atkInterval: 1500,
    range: 220,
    speed: 80,
    kb: 4,
    recast: 10800,
    strongAgainst: ['deep', 'red'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・超激レア。海面艦隊を率いる歴戦の提督。',
  },
  {
    id: 'cerberus',
    name: 'ケルベロス',
    breed: '冥府の番犬',
    role: '伝説の守護者',
    icon: '🔥',
    layer: 'ground',
    rarity: 'legend',
    cost: 400,
    hp: 900,
    atk: 260,
    atkInterval: 1000,
    range: 100,
    speed: 105,
    kb: 6,
    recast: 11000,
    strongAgainst: ['boss', 'ancient', 'alien'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・伝説レア。三つ首が同時に吠える、王国最強クラスの守護者。',
  },
  {
    id: 'fenrir',
    name: 'フェンリル',
    breed: '神話の巨狼',
    role: '破滅の一撃',
    icon: '🌑',
    layer: 'mid',
    rarity: 'legend',
    cost: 420,
    hp: 800,
    atk: 300,
    atkInterval: 1100,
    range: 90,
    speed: 120,
    kb: 6,
    recast: 11500,
    strongAgainst: ['void', 'black'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・伝説レア。中空を切り裂く神話の巨狼。その一撃は世界を揺るがす。',
  },
  {
    id: 'seiryu-inu',
    name: 'セイリュウ',
    breed: '神獣',
    role: '龍神の加護',
    icon: '🐉',
    layer: 'sky',
    rarity: 'legend',
    cost: 440,
    hp: 850,
    atk: 310,
    atkInterval: 1150,
    range: 150,
    speed: 125,
    kb: 6,
    recast: 12000,
    strongAgainst: ['angel', 'alien', 'boss'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ガチャ限定・伝説レア。上空を統べる龍神の化身。あらゆる強敵に牙を剥く。',
  },
  // ---- 追加キャラクター（レア1・EX3・超激レア5・伝説レア3） ----
  {
    id: 'popart-leopard',
    name: 'クロヒョウ',
    breed: '黒ヒョウ',
    role: '軽業強襲',
    icon: '🎨',
    layer: 'ground',
    rarity: 'rare',
    cost: 175,
    hp: 280,
    atk: 110,
    atkInterval: 950,
    range: 75,
    speed: 115,
    kb: 3,
    recast: 6200,
    strongAgainst: ['red', 'black'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'ポップアートの申し子。三原色のけん玉を華麗に操り、街角のリズムで敵を翻弄する。',
  },
  {
    id: 'kirin-gunner',
    name: 'キリン',
    breed: '麒麟',
    role: '氷結乱射',
    icon: '❄️',
    layer: 'mid',
    rarity: 'EX',
    cost: 300,
    hp: 480,
    atk: 180,
    atkInterval: 1000,
    range: 200,
    speed: 95,
    kb: 4,
    recast: 10500,
    strongAgainst: ['red', 'ancient'],
    startUnlocked: false,
    flavor: '自然の加護を受けた未来型ハンター。氷の光弾を雨のように降らせる。',
  },
  {
    id: 'zebra-mage',
    name: 'シマウマ',
    breed: 'シマウマ',
    role: '疾風魔導',
    icon: '🌪️',
    layer: 'ground',
    rarity: 'EX',
    cost: 320,
    hp: 440,
    atk: 190,
    atkInterval: 1050,
    range: 170,
    speed: 100,
    kb: 4,
    recast: 11000,
    strongAgainst: ['floating', 'alien'],
    startUnlocked: false,
    flavor: '宝石をまとった法衣の魔導師。金属の杖から突風の魔法を放つ。',
  },
  {
    id: 'kaba-gravity',
    name: 'カバ',
    breed: 'カバ',
    role: '重力波動',
    icon: '💥',
    layer: 'sea',
    rarity: 'EX',
    cost: 340,
    hp: 620,
    atk: 195,
    atkInterval: 1250,
    range: 140,
    speed: 80,
    kb: 5,
    recast: 12000,
    strongAgainst: ['red', 'deep'],
    startUnlocked: false,
    flavor: '数式とアラビア文字を纏う異能の賢者。炎と水がせめぎ合う重力波で敵をなぎ払う。',
  },
  {
    id: 'pearl-yoyo-poodle',
    name: 'パール',
    breed: 'トイプードル',
    role: '旋風連撃',
    icon: '💗',
    layer: 'mid',
    rarity: 'superrare',
    cost: 310,
    hp: 400,
    atk: 195,
    atkInterval: 950,
    range: 160,
    speed: 115,
    kb: 3,
    recast: 9800,
    strongAgainst: ['black', 'void'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: '輝くチアガール衣装のアイドル。無数のピンクパールを華麗に舞わせる。',
  },
  {
    id: 'shadow-blade-cat',
    name: 'シャドウ',
    breed: '黒猫',
    role: '影光剣士',
    icon: '⚔️',
    layer: 'ground',
    rarity: 'superrare',
    cost: 345,
    hp: 700,
    atk: 215,
    atkInterval: 1200,
    range: 70,
    speed: 85,
    kb: 5,
    recast: 10600,
    strongAgainst: ['angel', 'black'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: '黒光りする甲冑をまとう剣士。大量のシャドウソードを背負い、光と影の剣を同時に振るう。',
  },
  {
    id: 'kamaitachi-spear',
    name: 'カマイタチ',
    breed: 'カマイタチ',
    role: '疾風槍舞',
    icon: '⚡',
    layer: 'sky',
    rarity: 'superrare',
    cost: 330,
    hp: 450,
    atk: 225,
    atkInterval: 900,
    range: 100,
    speed: 140,
    kb: 4,
    recast: 10200,
    strongAgainst: ['floating', 'alien'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: '光輝く衣をまとう疾風の刃。槍を回転させ、炎と稲妻を同時に叩きつける。',
  },
  {
    id: 'kitsune-nezumi-duo',
    name: 'コンビ',
    breed: 'キツネ&ネズミ',
    role: '電炎二人衆',
    icon: '💫',
    layer: 'ground',
    rarity: 'superrare',
    cost: 335,
    hp: 480,
    atk: 220,
    atkInterval: 1000,
    range: 80,
    speed: 110,
    kb: 4,
    recast: 10400,
    strongAgainst: ['red', 'floating'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: '白装束に光のオーラを纏う名コンビ。電気のネズミと炎のキツネが息を合わせ、輝く剣を生み出す。',
  },
  {
    id: 'pegasus-hybrid',
    name: 'ペガサス',
    breed: '獅狼天馬',
    role: '氷翼降臨',
    icon: '🌬️',
    layer: 'sky',
    rarity: 'superrare',
    cost: 350,
    hp: 560,
    atk: 235,
    atkInterval: 1300,
    range: 190,
    speed: 120,
    kb: 5,
    recast: 11000,
    strongAgainst: ['angel', 'alien', 'boss'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: '獅子と狼を掛け合わせ、ペガサスの翼を宿した聖獣。氷柱フラッシュと光る突風で戦場を制す。',
  },
  {
    id: 'legend-fox-claw',
    name: 'ライコ',
    breed: '伝説のキツネ',
    role: '雷爪一閃',
    icon: '⚡',
    layer: 'ground',
    rarity: 'legend',
    cost: 460,
    hp: 880,
    atk: 330,
    atkInterval: 950,
    range: 90,
    speed: 135,
    kb: 6,
    recast: 12000,
    strongAgainst: ['alien', 'void', 'boss'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'イナヅマを纏う伝説の狐。輝く胴衣をひるがえし、雷を帯びたかぎ爪で敵を切り裂く。',
  },
  {
    id: 'cosmos-goddess',
    name: 'ギンガ',
    breed: '宇宙の女神',
    role: '星辰支配',
    icon: '🕳️',
    layer: 'sky',
    rarity: 'legend',
    cost: 480,
    hp: 820,
    atk: 340,
    atkInterval: 1250,
    range: 220,
    speed: 110,
    kb: 6,
    recast: 12500,
    strongAgainst: ['alien', 'void', 'boss'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'キングオブゴッドの名を持つ宇宙の女神。星々とブラックホールを自在に操り、七色の光を纏う。',
  },
  {
    id: 'elemental-husky-god',
    name: 'ゴッド',
    breed: 'シベリアンハスキー(神格)',
    role: '五元神威',
    icon: '🌊',
    layer: 'sea',
    rarity: 'legend',
    cost: 500,
    hp: 950,
    atk: 350,
    atkInterval: 1300,
    range: 200,
    speed: 100,
    kb: 7,
    recast: 13000,
    strongAgainst: ['deep', 'ancient', 'boss'],
    startUnlocked: false,
    gachaOnly: true,
    flavor: 'キングオブゴッドの名をもつ黒光りする神犬。五元素を統べ、雷を帯びた大津波で戦場ごと飲み込む。',
  },
];

export const GACHA_POOL = [
  // レア（9種、各6）
  { defId: 'dachs-fighter', weight: 6 },
  { defId: 'pome-sho', weight: 6 },
  { defId: 'beagle-scout', weight: 6 },
  { defId: 'shiba-ronin', weight: 6 },
  { defId: 'poodle-mage', weight: 6 },
  { defId: 'akita-guard', weight: 6 },
  { defId: 'whippet-dash', weight: 6 },
  { defId: 'labrador-diver', weight: 6 },
  { defId: 'popart-leopard', weight: 6 },
  // EX（8種、各7）
  { defId: 'corgi-commander', weight: 7 },
  { defId: 'moon-husky', weight: 7 },
  { defId: 'cosmo-bernese', weight: 7 },
  { defId: 'triton-hound', weight: 7 },
  { defId: 'ragna-emperor', weight: 7 },
  { defId: 'kirin-gunner', weight: 7 },
  { defId: 'zebra-mage', weight: 7 },
  { defId: 'kaba-gravity', weight: 7 },
  // 超激レア（10種、各2）
  { defId: 'greatdane-emperor', weight: 2 },
  { defId: 'mastiff-titan', weight: 2 },
  { defId: 'bordercollie-strategist', weight: 2 },
  { defId: 'shepherd-marshal', weight: 2 },
  { defId: 'newfoundland-admiral', weight: 2 },
  { defId: 'pearl-yoyo-poodle', weight: 2 },
  { defId: 'shadow-blade-cat', weight: 2 },
  { defId: 'kamaitachi-spear', weight: 2 },
  { defId: 'kitsune-nezumi-duo', weight: 2 },
  { defId: 'pegasus-hybrid', weight: 2 },
  // 伝説レア（6種、各1）
  { defId: 'cerberus', weight: 1 },
  { defId: 'fenrir', weight: 1 },
  { defId: 'seiryu-inu', weight: 1 },
  { defId: 'legend-fox-claw', weight: 1 },
  { defId: 'cosmos-goddess', weight: 1 },
  { defId: 'elemental-husky-god', weight: 1 },
];

export function getUnitDef(id) {
  return UNIT_DEFS.find((u) => u.id === id);
}

export function getLevelMultiplier(level) {
  const perLevel = 1 + (Math.max(1, level) - 1) * LEVEL_PER_STEP;
  return perLevel * FORM_BONUS[getFormIndex(level)];
}

// レーダーチャート用のステータス最大値（全キャラの基礎値中の最大値。正規化の基準にする）
const STAT_MAX = {
  hp: Math.max(...UNIT_DEFS.map((u) => u.hp)),
  atk: Math.max(...UNIT_DEFS.map((u) => u.atk)),
  range: Math.max(...UNIT_DEFS.map((u) => u.range)),
  speed: Math.max(...UNIT_DEFS.map((u) => u.speed)),
  kb: Math.max(...UNIT_DEFS.map((u) => u.kb)),
};

// レーダーチャート用に5軸（HP/攻撃/射程/速度/耐久）を0〜1に正規化して返す。
// HP・攻撃力はレベル補正後の値、射程・速度・耐久はレベルで変化しない基礎値を使う。
export function getRadarStats(def, level) {
  const mult = getLevelMultiplier(level);
  const hp = Math.round(def.hp * mult);
  const atk = Math.round(def.atk * mult);
  return [
    { label: 'HP', value: hp, ratio: Math.min(1, hp / STAT_MAX.hp) },
    { label: '攻撃', value: atk, ratio: Math.min(1, atk / STAT_MAX.atk) },
    { label: '射程', value: def.range, ratio: Math.min(1, def.range / STAT_MAX.range) },
    { label: '速度', value: def.speed, ratio: Math.min(1, def.speed / STAT_MAX.speed) },
    { label: '耐久', value: def.kb, ratio: Math.min(1, def.kb / STAT_MAX.kb) },
  ];
}

export function getUpgradeCost(def, currentLevel, limitBreakCount = 0) {
  const cap = getEffectiveMaxLevel(def, limitBreakCount);
  if (currentLevel >= cap) return null;
  return Math.round(def.cost * (1.5 + currentLevel * 0.5));
}

let uidCounter = 0;

export function spawnAlly(defId, x, level = 1) {
  const def = getUnitDef(defId);
  if (!def) throw new Error(`unknown unit: ${defId}`);
  const mult = getLevelMultiplier(level);
  return {
    uid: `a${++uidCounter}`,
    defId,
    side: 'ally',
    name: def.name,
    icon: def.icon,
    layer: def.layer,
    level,
    form: getFormIndex(level),
    x,
    width: 34,
    hp: Math.round(def.hp * mult),
    maxHp: Math.round(def.hp * mult),
    atk: Math.round(def.atk * mult),
    atkInterval: def.atkInterval,
    range: def.range,
    speed: def.speed,
    kbRemaining: def.kb,
    strongAgainst: def.strongAgainst,
    nextAttackAt: 0,
    attackFlashUntil: 0,
    knockbackUntil: 0,
    engaged: false,
    dead: false,
  };
}
